import Head from 'next/head';
import Header from '@/components/Header';
import styled from 'styled-components';
import { useState } from 'react';

export default function Home() {
  const [overlay, setOverlay] = useState(false);

  const toggleOverlay = () => {
    setOverlay(!overlay);
  }

  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header toggleOverlay={toggleOverlay} />
      <main>
        <div className={`overlay ${overlay ? 'show__overlay' : ''}`}></div>
      </main>
    </Wrapper>
  )
}

const Wrapper = styled.div`
  position: relative;

  .overlay {
    opacity: 0;
    position: absolute;
    top: 0;
    left: 0;
    background-color: ${props => props.theme.colors.black};
    height: 100vh;
    width: 100%;
    transition: 200ms;
    pointer-events: none;
  }

  .show__overlay {
    opacity: 0.8;
    transition-delay: 200ms;
    transition: 300ms;
  }
`